# Setup
title:               HY
tagline:             'Newest Developer'
description:         '초급 개발자 윤희영 기술 블로그 by Git'
url:                 https://dgd2763.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hee Young
  url:               ''
  email:             dgd2763@naver.com

category_dir:        category/
tag_dir:             tag/
# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
